apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mbwi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-ugpl-tenant/byoc-app-yitv/mbwi@sha256:1fc4d523814a1b064638a8f3a47249f36386da62ac468130b4ba9df085f77d36
        name: my-java-quarkus
        resources: {}
status: {}
