apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mbwi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbwi
    app.kubernetes.io/part-of: byoc-app-yitv
  name: mbwi
spec:
  rules:
  - host: mbwi-byoc-ugpl-tenant.apps.46d35cd2f0a3b7f466e8.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: mbwi
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
