apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mbwi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbwi
    app.kubernetes.io/part-of: byoc-app-yitv
  name: mbwi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: mbwi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: mbwi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ugpl-tenant/byoc-app-yitv/mbwi@sha256:1fc4d523814a1b064638a8f3a47249f36386da62ac468130b4ba9df085f77d36
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
